import Foundation
import Testing

/// Pins `THIRD_PARTY_NOTICES.md` (generated by `scripts/third-party-notices`,
/// see that script's header comment) to `Package.resolved`: every pinned
/// dependency must have its own `## <identity>` section in the notices file.
///
/// The check reads both files fresh from the repository root — it derives
/// the expected identities from `Package.resolved`'s JSON (`pins[].identity`)
/// rather than from a typed list copied into this file, so a dependency
/// added, removed or renamed in `Package.resolved` changes what this test
/// expects without anyone having to update a second list here (CLAUDE.md,
/// "A guard that spells a symbol it could read instead is waiting for a
/// rename").
///
/// "Every identity has a heading" is, on its own, a check that a JSON parse
/// failure or an empty `pins` array would satisfy vacuously — a missing or
/// unreadable `Package.resolved` looks identical to a project with zero
/// dependencies. `thePinCountIsWellAboveZero` and
/// `theNoticesFileHasAtLeastOneDependencySection` are the positive anchors
/// beside it (CLAUDE.md, "Guards that name what they watch": a negative
/// check needs a positive check beside it asserting the thing it scans is
/// there at all).
@Suite("Third-party notices match Package.resolved")
struct ThirdPartyNoticesTests {
    /// `#filePath` here is
    /// `<repoRoot>/Tests/macSCPCoreTests/ThirdPartyNoticesTests.swift`;
    /// three `deletingLastPathComponent()` calls recover the repo root
    /// regardless of `swift test`'s working directory (same trick as
    /// `CLISessionsCommandGuardTests` and
    /// `CitadelFileSystemConnectTimeoutWiringGuardTests`).
    private static let repoRoot: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent()

    private static let packageResolvedFile = repoRoot
        .appendingPathComponent("Package.resolved")

    private static let noticesFile = repoRoot
        .appendingPathComponent("THIRD_PARTY_NOTICES.md")

    /// `pins[].identity`, parsed straight out of the JSON — no typed
    /// `Codable` model, no separate list a rename could leave stale. Traps
    /// (via `try!`) rather than returning an empty array on a malformed
    /// file: a parse failure must be loud, not quietly read as "zero
    /// pins", which is exactly the shape `thePinCountIsWellAboveZero` below
    /// exists to catch if it ever did happen.
    private static func pinIdentities() throws -> [String] {
        let data = try Data(contentsOf: packageResolvedFile)
        let root = try #require(
            try JSONSerialization.jsonObject(with: data) as? [String: Any])
        let pins = try #require(root["pins"] as? [[String: Any]])
        return pins.compactMap { $0["identity"] as? String }
    }

    /// Section headings in the notices file, taken from lines that are
    /// EXACTLY `## <name>` — not merely lines containing `## ` as a
    /// substring. Several of the embedded licence texts (the Apache 2.0
    /// runtime-library exception, copied verbatim into more than one
    /// dependency's section) contain a line reading `## Runtime Library
    /// Exception to the Apache 2.0 License: ##`, which starts with `## ` the
    /// same as a real section heading. Matching the whole line rather than
    /// a prefix keeps those decoys from being counted as dependency
    /// sections.
    private static func sectionHeadings(in notices: String) -> Set<String> {
        var headings: Set<String> = []
        notices.enumerateLines { line, _ in
            if line.hasPrefix("## ") {
                headings.insert(String(line.dropFirst(3)))
            }
        }
        return headings
    }

    // MARK: - Positive anchors

    @Test func thePinCountIsWellAboveZero() throws {
        let identities = try Self.pinIdentities()
        #expect(identities.count > 5, """
            Package.resolved parsed to only \(identities.count) pin(s) — \
            either the pin list genuinely shrank far below its current 12 \
            dependencies, or the parse silently read the wrong shape. \
            Without this anchor, an empty or misread pins array would make \
            everyNoticeSectionExists() below pass vacuously (CLAUDE.md, \
            "Guards that name what they watch").
            """)
    }

    @Test func theNoticesFileHasAtLeastOneDependencySection() throws {
        let notices = try String(contentsOf: Self.noticesFile, encoding: .utf8)
        let headings = Self.sectionHeadings(in: notices)
        #expect(!headings.isEmpty, """
            THIRD_PARTY_NOTICES.md has no `## <name>` section heading at \
            all — an empty or malformed notices file would otherwise make \
            everyNoticeSectionExists() below fail for a reason unrelated to \
            missing pins, or (if it read as containing every identity by \
            accident) pass vacuously.
            """)
    }

    // MARK: - The pin

    @Test func everyNoticeSectionExists() throws {
        let identities = try Self.pinIdentities()
        let notices = try String(contentsOf: Self.noticesFile, encoding: .utf8)
        let headings = Self.sectionHeadings(in: notices)
        let missing = identities.filter { !headings.contains($0) }
        #expect(missing.isEmpty, """
            THIRD_PARTY_NOTICES.md is missing a `## <identity>` section for \
            \(missing) — every pin in Package.resolved needs its own \
            notice section. Regenerate with `scripts/third-party-notices` \
            from the repository root.
            """)
    }
}
