import Foundation
import Testing

/// Pins `THIRD_PARTY_NOTICES.md` (generated by `scripts/third-party-notices`,
/// see that script's header comment) to `Package.resolved`: every pinned
/// dependency must have its own `## <identity>` section in the notices file.
///
/// The check reads both files fresh from the repository root — it derives
/// the expected identities from `Package.resolved`'s JSON (`pins[].identity`)
/// rather than from a typed list copied into this file, so a dependency
/// added, removed or renamed in `Package.resolved` changes what this test
/// expects without anyone having to update a second list here (CLAUDE.md,
/// "A guard that spells a symbol it could read instead is waiting for a
/// rename").
///
/// "Every identity has a heading" is, on its own, a check that a JSON parse
/// failure or an empty `pins` array would satisfy vacuously — a missing or
/// unreadable `Package.resolved` looks identical to a project with zero
/// dependencies. `thePinCountIsWellAboveZero` and
/// `theNoticesFileHasAtLeastOneDependencySection` are the positive anchors
/// beside it (CLAUDE.md, "Guards that name what they watch": a negative
/// check needs a positive check beside it asserting the thing it scans is
/// there at all).
@Suite("Third-party notices match Package.resolved")
struct ThirdPartyNoticesTests {
    /// `#filePath` here is
    /// `<repoRoot>/Tests/macSCPCoreTests/ThirdPartyNoticesTests.swift`;
    /// three `deletingLastPathComponent()` calls recover the repo root
    /// regardless of `swift test`'s working directory (same trick as
    /// `CLISessionsCommandGuardTests` and
    /// `CitadelFileSystemConnectTimeoutWiringGuardTests`).
    private static let repoRoot: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent()

    private static let packageResolvedFile = repoRoot
        .appendingPathComponent("Package.resolved")

    private static let noticesFile = repoRoot
        .appendingPathComponent("THIRD_PARTY_NOTICES.md")

    /// `pins[].identity`, parsed straight out of the JSON — no typed
    /// `Codable` model, no separate list a rename could leave stale. Traps
    /// (via `try!`) rather than returning an empty array on a malformed
    /// file: a parse failure must be loud, not quietly read as "zero
    /// pins", which is exactly the shape `thePinCountIsWellAboveZero` below
    /// exists to catch if it ever did happen.
    private static func pinIdentities() throws -> [String] {
        let data = try Data(contentsOf: packageResolvedFile)
        let root = try #require(
            try JSONSerialization.jsonObject(with: data) as? [String: Any])
        let pins = try #require(root["pins"] as? [[String: Any]])
        return pins.compactMap { $0["identity"] as? String }
    }

    /// Section headings in the notices file, taken from lines that start
    /// with `## ` OUTSIDE a fenced licence block. Two distinct decoy risks
    /// live in the file's embedded licence texts:
    ///
    /// - Several copies of the Apache 2.0 runtime-library exception
    ///   contain a line reading `## Runtime Library Exception to the
    ///   Apache 2.0 License: ##`, which starts with `## ` the same as a
    ///   real heading but never equals a bare identity — `dropFirst(3)`
    ///   on it does not collide with any of the 12 real identities today.
    /// - A licence or NOTICE file, copied verbatim, could itself quote a
    ///   line that reads exactly `## <some real identity>` — that one WOULD
    ///   collide, and nothing about its text distinguishes it from a real
    ///   heading. Only its position — inside a fence — does. So this
    ///   function tracks fence state and only collects `## ` lines while
    ///   outside one (task-2 review, "Important" finding).
    ///
    /// Fence delimiters are matched by PREFIX — three or more backticks —
    /// not by the exact three-backtick string ` ``` `. The generator
    /// (`scripts/third-party-notices`, `fence_for`) widens a licence
    /// file's own fence past the longest backtick run already present in
    /// that licence's text, so a fence-length check pinned to exactly
    /// ``` would itself go stale the moment a quoted licence needed a
    /// longer one; matching any run of three or more keeps every open/close
    /// pair recognized regardless of length, since each pair only needs to
    /// toggle the same boolean, not agree on a specific count.
    private static func sectionHeadings(in notices: String) -> Set<String> {
        var headings: Set<String> = []
        var insideFence = false
        notices.enumerateLines { line, _ in
            if Self.isFenceDelimiter(line) {
                insideFence.toggle()
                return
            }
            if !insideFence, line.hasPrefix("## ") {
                headings.insert(String(line.dropFirst(3)))
            }
        }
        return headings
    }

    /// True when `line`'s leading run of backticks (after trimming
    /// surrounding whitespace) is three or more — a markdown fence
    /// delimiter, open or close, of any length the generator might have
    /// chosen for this particular licence text.
    private static func isFenceDelimiter(_ line: String) -> Bool {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        var run = 0
        for character in trimmed {
            guard character == "`" else { break }
            run += 1
        }
        return run >= 3
    }

    // MARK: - Positive anchors

    @Test func thePinCountIsWellAboveZero() throws {
        let identities = try Self.pinIdentities()
        #expect(identities.count > 5, """
            Package.resolved parsed to only \(identities.count) pin(s) — \
            either the pin list genuinely shrank far below its current 12 \
            dependencies, or the parse silently read the wrong shape. \
            Without this anchor, an empty or misread pins array would make \
            everyNoticeSectionExists() below pass vacuously (CLAUDE.md, \
            "Guards that name what they watch").
            """)
    }

    /// A scanner self-test, independent of anything the real notices file
    /// happens to contain today: a `## swift-log`-shaped line sitting
    /// INSIDE a fenced licence block (a licence or NOTICE file, copied
    /// verbatim, can itself quote something that looks exactly like a
    /// section heading) must not count as a real section. Proves the
    /// scanner tracks fence state rather than matching `## <name>` lines
    /// wherever they occur in the file — the gap flagged in the task-2
    /// review: without fence tracking, a fenced decoy matching a real
    /// identity would stand in for that identity's real (missing) section
    /// and let `everyNoticeSectionExists` pass regardless.
    ///
    /// The fixture's fence uses four backticks, not three — the generator
    /// (`scripts/third-party-notices`, `fence_for`) widens a licence
    /// file's fence past the longest backtick run already inside that
    /// licence text, so a fence-length check pinned to exactly ``` would
    /// itself go stale the first time a quoted licence needed a longer
    /// one. Detection here is by PREFIX (three or more backticks), so a
    /// four-backtick fence toggles state exactly like a three-backtick one.
    @Test func aHeadingLineInsideALicenceFenceIsNotASection() {
        let fixture = """
            ## swift-crypto

            Source: <https://example.invalid/swift-crypto>

            ### LICENSE

            ````
            Some licence text that happens to quote another project's
            NOTICE file, including a line that reads exactly:
            ## swift-log
            ````

            ## swift-nio
            """
        let headings = Self.sectionHeadings(in: fixture)
        #expect(!headings.contains("swift-log"), """
            sectionHeadings(in:) counted a `## swift-log` line that sits \
            inside a fenced licence block as a real section heading — a \
            fence must suppress every `## ` line between its open and \
            close delimiter, not just the specific decoy strings the real \
            file happens to contain today.
            """)
        #expect(headings == ["swift-crypto", "swift-nio"], """
            expected only the two real, unfenced headings in the fixture \
            (swift-crypto, swift-nio), got \(headings) instead — either \
            the fence swallowed a real heading, or let the decoy through.
            """)
    }

    @Test func theNoticesFileHasAtLeastOneDependencySection() throws {
        let notices = try String(contentsOf: Self.noticesFile, encoding: .utf8)
        let headings = Self.sectionHeadings(in: notices)
        #expect(!headings.isEmpty, """
            THIRD_PARTY_NOTICES.md has no `## <name>` section heading at \
            all — an empty or malformed notices file would otherwise make \
            everyNoticeSectionExists() below fail for a reason unrelated to \
            missing pins, or (if it read as containing every identity by \
            accident) pass vacuously.
            """)
    }

    // MARK: - The pin

    @Test func everyNoticeSectionExists() throws {
        let identities = try Self.pinIdentities()
        let notices = try String(contentsOf: Self.noticesFile, encoding: .utf8)
        let headings = Self.sectionHeadings(in: notices)
        let missing = identities.filter { !headings.contains($0) }
        #expect(missing.isEmpty, """
            THIRD_PARTY_NOTICES.md is missing a `## <identity>` section for \
            \(missing) — every pin in Package.resolved needs its own \
            notice section. Regenerate with `scripts/third-party-notices` \
            from the repository root.
            """)
    }
}
